### ISSUE TITLE
What is the best way to use elasticsearch as services in GHA

### ISSUE THREAD

**Issue by sh977218** [elastic/elastic-github-actions#44]
```
jobs:
  buikd:
    name: build
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: elastic/elastic-github-actions/elasticsearch@master
        /*         how do I specific the volume/es's version etc here?
         **
         */
        ports:
        - 9200:9200
    steps:
      - run: curl -X GET http://localhost:9200/_cluster/health
```

**Comment by picandocodigo** [comment]
Hi @sh977218, 
I think for using Elasticsearch as a service in GitHub Actions, you'd have to use the docker images instead of this action. 

This is **untested code**, but you can try something like this:
```yaml
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:VERSION
        ports:
        - 9200:9200
```

You can probably pass in the volumes as an option key, something like:

```yaml
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:VERSION
        options: >-
           --volume example:example
        ports:
        - 9200:9200
```

Hope this helps.

**Comment by sh977218** [comment]
Hi, @picandocodigo  If I remove those 2 lines below, the workflow works fine, as you suggested. Thanks!
```
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-noble
```

However, if I use playwright docker image in the workflow, it does not work anymore. Do you know how to fix this?
```
name: tests
on:
  pull_request:

jobs:
  es-as-service:
    name: Start es as service
    runs-on: ubuntu-latest
    services:
      elasticsearch:
        image: docker.elastic.co/elasticsearch/elasticsearch:7.9.2
        env:
            discovery.type: single-node
        options:
          --health-cmd "curl http://localhost:9200/_cluster/health"
          --health-interval 10s
          --health-timeout 30s
          --health-retries 10
        ports:
          - 9200:9200
    container:
      image: mcr.microsoft.com/playwright:v1.46.0-noble
    steps:
      - uses: actions/checkout@v4

      - run: curl -X GET http://localhost:9200/_cluster/health

      - name: Create es index
        run: curl -X PUT "localhost:9200/heroes"

      - name: Inject data into es
        run: |
          curl -XPOST http://localhost:9200/heroes/doc -H "Content-Type: application/json" -d @test/heroes.json

      - run: curl http://localhost:9200/heroes/_search
```
